version: "2"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo:3.4.3
    volumes:
      - /data/db:/data/db
    ports:
      - "27017:27017"